# 核心守护脚本（监听 / 绑定）


```python
#!/usr/bin/env bash
set -euo pipefail

# ========== S1 固定策略配置 ==========
PREFER_IP="192.168.31.133"
ENV_FILE="$HOME/.swarmplug_env.sh"
POLL_INTERVAL_SEC=2
SCAN_PY="$HOME/swarmplus_ver1.0/catkin_ws/src/swarmplus_core/scripts/scan_ros_masters.py"

# 展示话题时最多显示多少行（避免太长）
TOPIC_LIST_LINES=80

log() { echo "[$(date '+%F %T')] $*"; }

local_ip_guess() {
  python3 - <<'PY'
import socket
s=socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
try:
  s.connect(("8.8.8.8",80))
  print(s.getsockname()[0])
except Exception:
  print("127.0.0.1")
finally:
  s.close()
PY
}

write_env() {
  local master_ip="$1"
  local local_ip="$2"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by swarmplug_start.sh (ver0.1, S1 fixed host)
export ROS_MASTER_URI=http://${master_ip}:11311
export ROS_HOSTNAME=${local_ip}
export ROS_IP=${local_ip}
EOF
}

prefer_found() {
  local scan_out="$1"
  echo "$scan_out" | awk '{print $1}' | grep -qx "$PREFER_IP"
}

format_candidates() {
  local scan_out="$1"
  if [[ -z "$scan_out" ]]; then
    echo "(none)"
  else
    echo "$scan_out" | awk '{print $1}' | paste -sd "," -
  fi
}

show_topics_once() {
  log "[INFO] echo \$ROS_MASTER_URI -> ${ROS_MASTER_URI:-"(empty)"}"
  log "[INFO] rostopic list (first ${TOPIC_LIST_LINES} lines):"
  # rostopic 失败不让脚本退出（宿主刚起来时可能短暂不可用）
  set +e
  rostopic list 2>&1 | sed -n "1,${TOPIC_LIST_LINES}p"
  local rc=$?
  set -e
  if [[ $rc -ne 0 ]]; then
    log "[WARN] rostopic list failed (master may be initializing). Will keep listening."
  fi
}

log "[SwarmPlug] ver0.1 start (S1 fixed host = ${PREFER_IP})"
[[ -x "$SCAN_PY" ]] || { log "[ERROR] scan script missing: $SCAN_PY"; exit 1; }

LOCAL_IP="$(local_ip_guess)"

STATE="LISTENING"          # LISTENING | READY
LAST_CANDIDATES="__init__" # 用于检测候选列表变化，避免刷屏

while true; do
  SCAN_OUT="$(python3 "$SCAN_PY" 2>/dev/null || true)"
  CANDIDATES="$(format_candidates "$SCAN_OUT")"

  if [[ "$CANDIDATES" != "$LAST_CANDIDATES" ]]; then
    log "[INFO] roscore candidates: $CANDIDATES"
    LAST_CANDIDATES="$CANDIDATES"
  fi

  if prefer_found "$SCAN_OUT"; then
    if [[ "$STATE" != "READY" ]]; then
      log "[OK] Preferred host found: ${PREFER_IP}. Binding..."
      write_env "$PREFER_IP" "$LOCAL_IP"

      # 让本脚本立即生效（注意：不会影响其他终端）
      # shellcheck disable=SC1090
      source "$ENV_FILE"

      log "[OK] Bound."
      log "[OK] ROS_MASTER_URI=$ROS_MASTER_URI"
      log "[OK] ROS_IP=${ROS_IP:-} ROS_HOSTNAME=${ROS_HOSTNAME:-}"
      log "[SwarmPlug] Ready. (ver0.1: no plugin auto-launched)"

      # ✅ 你要求的：监听到了就展示一次话题
      show_topics_once

      STATE="READY"
    fi
  else
    if [[ "$STATE" != "LISTENING" ]]; then
      log "[WARN] Preferred host lost (${PREFER_IP}). Back to listening..."
      STATE="LISTENING"
      unset ROS_MASTER_URI ROS_HOSTNAME ROS_IP || true
    fi
  fi

  sleep "$POLL_INTERVAL_SEC"
done


```
